@baseUrl = http://localhost:3000
@commentId = 69d583a489060222c8d778e4
@taskId = 69d5821689060222c8d778dd  
@userId = 69d57f3689060222c8d778c9

###
GET {{baseUrl}}/comments

###
GET {{baseUrl}}/comments/{{commentId}}

###
POST {{baseUrl}}/comments
Content-Type: application/json

{
  "taskId": "{{taskId}}",
  "userId": "{{userId}}",
  "content": "Project CRUD is working well. Next I am validating the task endpoints."
}

###
PUT {{baseUrl}}/comments/{{commentId}}
Content-Type: application/json

{
  "content": "Updated comment content from REST client."
}

###
DELETE {{baseUrl}}/comments/{{commentId}}