@baseUrl = http://localhost:3000
@userId = 69d57f3689060222c8d778c9

###
GET {{baseUrl}}/users

###
GET {{baseUrl}}/users/{{userId}}

###
POST {{baseUrl}}/users
Content-Type: application/json

{
  "firstName": "Edwin",
  "lastName": "Bwambale",
  "email": "edwin.one@example.com",
  "role": "admin",
  "phone": "+256700000001",
  "isActive": true
}

###
PUT {{baseUrl}}/users/{{userId}}
Content-Type: application/json

{
  "firstName": "Edwin Updated",
  "phone": "+256700000999",
  "isActive": true
}

###
DELETE {{baseUrl}}/users/{{userId}}