@baseUrl = http://localhost:3000
@contactId = 69ac2e7158ea35a821127061
@missingId = 507f1f77bcf86cd799439011

GET {{baseUrl}}/

GET {{baseUrl}}/contacts

GET {{baseUrl}}/contacts/{{contactId}}

POST {{baseUrl}}/contacts
Content-Type: application/json

{
  "firstName": "Joshua",
  "lastName": "Asiimwe",
  "email": "joshua.asiimwe@example.com",
  "favoriteColor": "Orange",
  "birthday": "2001-12-10"
}

POST {{baseUrl}}/contacts
Content-Type: application/json

{
  "firstName": "Incomplete",
  "lastName": "User"
}

PUT {{baseUrl}}/contacts/{{contactId}}
Content-Type: application/json

{
  "firstName": "Grace",
  "lastName": "Auma",
  "email": "grace.updated@example.com",
  "favoriteColor": "Lavender",
  "birthday": "2001-01-24"
}

PUT {{baseUrl}}/contacts/123
Content-Type: application/json

{
  "firstName": "Bad",
  "lastName": "Id",
  "email": "badid@example.com",
  "favoriteColor": "Gray",
  "birthday": "2000-01-01"
}

PUT {{baseUrl}}/contacts/{{missingId}}
Content-Type: application/json

{
  "firstName": "Ghost",
  "lastName": "User",
  "email": "ghost@example.com",
  "favoriteColor": "Transparent",
  "birthday": "1990-01-01"
}

DELETE {{baseUrl}}/contacts/{{contactId}}

DELETE {{baseUrl}}/contacts/abc

DELETE {{baseUrl}}/contacts/{{missingId}}