### Get all contacts (local)
GET http://localhost:3000/contacts
Accept: application/json

###

# the _id value (69ac2e7158ea35a821127061) is from the contacts collection for one of the objects i created inside the mongo db
GET http://localhost:3000/contacts/69ac2e7158ea35a821127061
Accept: application/json

### Get all contacts (Render)
GET https://cse341-sgi5.onrender.com
Accept: application/json
